name: update awesome-stars
on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:
jobs:
  awesome-stars:
    name: update awesome-stars
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install starred
    - name: update starred.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: starred --username JackTheMico --token ${GITHUB_TOKEN} --sort > starred.md
    - uses: EndBug/add-and-commit@v9
      with:
        add: 'starred.md'
        committer_name: GitHub Actions
        committer_email: actions@github.com
        message: 'update starred.md'
        push: true
