# forked from https://github.com/ouuan/ouuan/blob/master/.github/workflows/topFollowers.yml
name: Get Top Followers
on:
  schedule:
    - cron: '0 20 15 * *'
  workflow_dispatch:
jobs:
  top-followers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install requests
        run: pip install requests
      - name: Update README
        run: python getTopFollowers.py ${{ github.repository_owner }} ${{ secrets.GH_TOKEN }} README.md
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Update top followers"
      - name: Pull changes
        run: git pull -r
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
