name: Latest blog post workflow
on:
  repository_dispatch:
    types: [update_profile]

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update hugo blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://jackthemico.github.io/index.xml"
          max_post_count: 7
