# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each 72 hours)
  schedule: [{ cron: "0 0/72 * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
    push:
      branches:
        - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          # Your GitHub token
          token: ${{ secrets.gh_TOKEN }}

          # Options
          user: JackTheMico
          output_action: commit
          committer_branch: main
          committer_message: "Regular update metrics"
          template: classic
          base: header, activity, repositories, metadata
          config_timezone: Asia/Shanghai
          commits_authoring: "Jack Wenyoung, jackwenyoung"
          # Plugins
          # commits calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          # Language Activity
          plugin_languages: yes
          # Lines of code changed
          plugin_lines: yes
          # Follow-up of issues and pull requests
          plugin_followup: yes
          # Introduction
          plugin_introduction: yes
          plugin_introduction_title: yes
          # Wakatime
          plugin_wakatime: yes
          plugin_wakatime_days: 365
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY}}
          # LeetCode
          plugin_leetcode: no
          plugin_leetcode_user: jackwenyoung
          # traffic
          plugin_traffic: yes
          # Rss
          plugin_rss: no
          plugin_rss_source: https://jackwenyoung.com/rss.xml
          # website screenshot
          plugin_screenshot: yes
          plugin_screenshot_title: "jackwenyoung.com"
          plugin_screenshot_url: https://jackwenyoung.com/en
          # fortune
          plugin_fortune: yes
  update-blog:
    name: Update latest blogs
    runs-on: ubuntu-latest
    if: ${{ always() }} # Make this always run
    needs: github-metrics
    steps:
      - uses: actions/checkout@v4
      - uses: imskr/readme-update-actions@v2.1
        with:
          rss_list: "https//jackwenyoung.com/rss.xml"
